-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jun 28, 2019 at 01:15 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sunglass`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `username` varchar(252) NOT NULL,
  `password` int(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `static_sunglasses`
--

CREATE TABLE `static_sunglasses` (
  `id` int(11) NOT NULL,
  `img` varchar(400) NOT NULL,
  `price` varchar(50) NOT NULL,
  `availibility` int(50) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `vir_sunglasses`
--

CREATE TABLE `vir_sunglasses` (
  `id` int(11) NOT NULL,
  `sku` varchar(400) NOT NULL,
  `price` varchar(252) NOT NULL,
  `img` varchar(252) NOT NULL,
  `description` text NOT NULL,
  `availibility` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `vir_sunglasses`
--

INSERT INTO `vir_sunglasses` (`id`, `sku`, `price`, `img`, `description`, `availibility`) VALUES
(4, 'rayban_aviator_or_vertFlash', '$153', 'uploads/055566dd6e.jpg', 'This is the latest product we have. ', 0),
(5, 'rayban_wayfarer_havane_vert', '$203.00', 'uploads/0844ac549b.jpg', '', 0),
(6, 'rayban_wayfarer_denimOrange_orangeDegrade', '14,400?', 'uploads/94a0958e3e.jpg', 'Ray-Ban RB2140 Wayfarer Sunglasses Orange Jeans w/Orange Gradient (1165/3C) RB 2140 11653C 50mm is the new version of previous one.\r\n\r\nIt has some new feature.', 0),
(7, 'rayban_round_gun_vert', '$203.00', 'uploads/3bb7983d5f.jpg', 'A-Roval brings a modern twist to a classic style with fresh colors.There are many colours of The A-Roval sunglasses. The unique frame design has become an iconic fixture of pop culture fashion.Your new pair of A-Roval shades was created on the principle of genuine protection and quality craftsmanship.Our Sunglasses have some different styles.\r\n', 0),
(8, 'rayban_aviator_gun_vert', 'USD 19.99', 'uploads/69e7a70b7b.jpg', '\r\n2018 rayban glassess rayban ray', 0),
(9, 'rayban_round_gun_vert', '$203.00', 'uploads/d439d93ca6.jpg', 'A-Roval brings a modern twist to a classic style with fresh colors.There are many colours of The A-Roval sunglasses. The unique frame design has become an iconic fixture of pop culture fashion.Your new pair of A-Roval shades was created on the principle of genuine protection and quality craftsmanship.Our Sunglasses have some different styles.\r\n', 0),
(10, 'rayban_aviator_or_vert', '$55.00', 'uploads/b3cc799fd7.jpg', 'Wsunglass W925 Gold Frame Crystal Green Lens Men Women Sunglasses 58mm RB3025', 0),
(11, 'rayban_round_cuivre_pinkBrownDegrade', '$ 153.00', 'uploads/b04d48b0ee.jpg', 'Model code: RB3447 001 50-21\r\n\r\nThe Ray-Ban ® Round Metal sunglasses are totally retro. This look has been worn by legendary musicians and inspired by the 1960s counter-culture when this style first originated.The Ray-Ban unisex metal, iconic sunglasses are known for their defined round crystal lenses and distinct shape. A curved brow bar, adjustable nose pads, and thin metal temples with plastic end tips rest comfortably behind the ears.', 0),
(12, 'rayban_erika_marronArgent_marronVioletDegrade', 'US$150.15', 'uploads/fdcbb66fc9.jpg', 'Slender, matte frames surround the gradient lenses of these Ray-Ban sunglasses. A keyhole bridge and glossy metal arms reinforce the contemporary style. Case and cleaning cloth included.\r\nWayfarer-style sunglasses featuring gradient lenses and metal arms with tonal temple tips\r\nRay-Ban sizes refer to the width of one lens in millimeters and lenses are prescription ready (Rx-able).\r\nRay-Ban products sold by authorized sellers, like Amazon.com, are eligible for all manufacturer warranties and guarantees.\r\nProtective case included', 0),
(13, 'rayban_clubround_noir_cuivre_flash', '98.400 OMR', 'uploads/284845c8f1.jpg', 'Acetate,Metal Frames\r\n\r\nImported\r\n\r\nAcetate frame\r\n\r\nGlass lens\r\n\r\nNon-Polarized\r\n\r\n100% UV protection coating\r\n\r\nLens width: 51 millimeters\r\n\r\nBridge: 19 millimeters\r\n\r\nArm: 145 millimeters\r\n\r\n2.5" high\r\n\r\n0.3" wide\r\n\r\nCase included\r\n\r\nLenses are prescription ready (rx-able)\r\n\r\nNew club round shape club master meets round new addition to icons\r\n\r\nImported from USA\r\n\r\nRB4246 Clubround Sunglasses feature an acetate and metal frame and round lenses. The unisex RB4246 Clubround Sunglasses \r\nare marriage of the popular Clubmaster and Round styles and they available in a variety of frame colors and lens \r\ntreatments including polarized, gradient, solid and mirrored. To protect your eyes from harmful UV rays, these\r\nsunglasses include lenses that are coated with 100% UV protection.\r\n\r\nRay-Ban is the world''s most iconic eyewear brand and is a global leader in its sector. Every model in the Ray-Ban \r\ncollection is the product of meticulous, original styling that translates the best of the latest fashion trends into an \r\never-contemporary look for millions of Ray-Ban wearers around the world. From the early Aviator style that emerged in \r\n1937 to the introduction of the classic Wayfarer in 1952, Ray-Ban is a brand that embodies America and adventure, great \r\ncities and wide-open spaces, heroism, individuality, and authenticity. Starting with a silver screen debut in 1961, \r\nRay-Ban sunglasses have appeared throughout hundreds of films and have been a favorite on the Hollywood scene for years, \r\nboth on and off the screen. With timeless and imaginative styles, Ray-Ban consistently blends high-tech design, lenses, \r\nand materials. The collection remains true to its classic heritage while continuously evolving to meet today''s fashion \r\ndemands.\r\n\r\nRay-Ban is the world''s most iconic eyewear brand and is a global leader in its sector. Every model in the \r\nRay-Ban collection is the product of meticulous, original styling that translates the best of the latest fashion trends \r\ninto an ever-contemporary look for millions of Ray-Ban wearers around the world. From the early Aviator style that \r\nemerged in 1937 to the introduction of the classic Wayfarer in 1952, Ray-Ban is a brand that embodies America and \r\nadventure, great cities and wide-open spaces, heroism, individuality, and authenticity. Starting with a silver screen \r\ndebut in 1961, Ray-Ban sunglasses have appeared throughout hundreds of films and have been a favorite on the Hollywood \r\nscene for years, both on and off the screen. With timeless and imaginative styles, Ray-Ban consistently blends high-tech \r\ndesign, lenses, and materials. The collection remains true to its classic heritage while continuously evolving to meet \r\ntoday''s fashion demands.', 0),
(14, 'rayban_cockpit_or_vert_classique', '$153.00', 'uploads/e72df04d98.jpg', '100% Genuine Authentic Ray Ban Cockpit sunglasses in an official Ray Ban colored box & manual\r\nRayBan Sunglass case\r\nRay Ban Cleaning Cloth\r\nThis model of Ray Ban Sunglasses can be made with Prescription lenses to your exact specifications. If you need a single vision (far, near or computer distance) RX version of this Ray-Ban glasses frame, please see our Ray Ban Cockpit RB3362 Prescription sunglasses page for ordering info. If you are looking for Ray-Ban RB3362 with multifocal (lined bifocal or no-line progressive) lenses, please have a look at Ray Ban Prescription RB3362 Progressive Sunglasses and Ray-Ban RB3362 Prescription Bi-focal Sunglasses. For other Prescription Ray Ban Sunglasses please see our RayBan RX Page. We also offer Ray-Ban Prescription Eyeglasses with custom-made Rx lenses.\r\n\r\nAvailable Ray-Ban RB3362 Sunglasses:\r\n\r\nRay Ban RB3362 sunglasses\r\nRay Ban RB3362 prescription sunglasses\r\nRay Ban RB3362 prescription sunglasses with Bifocal lenses\r\nRay-Ban RB3362 prescription sunglasses with Progressive lenses\r\nRay Ban is a Luxottica brand, and all sunglasses, eyeglasses frames, and othereyewear purchased from us, an Authorized US Luxottica RayBan Dealer, are brand new and come with a one-year Ray-Ban / Luxottica warranty from the date of purchase, and in addition you get a piece of mind of our 100% Satisfaction Guarantee from us.', 0),
(15, 'rayban_justin_noir_rougeMirroir', 'R 4 790', 'uploads/efe12d42d5.jpg', 'Features\r\nRB4165 622/6Q 55-16-145\r\nMatte Black / Red Mirror\r\nProtective case included, cases come in a variety of colors.\r\nThe shape and curvature of these sunglasses may need adjustments. Adjustments should only be made by a professional.\r\nBuy with confidence. All of our Ray-Ban''s come straight from the manufacturer.\r\n\r\nOriginal RayBan RB4165 622/6Q Rubber Black/Brown Mirror Orange Size 54 mm Sunglasses.', 0),
(16, 'rayban_clubround_noir_vertClassique_g15', 'US$171.15', 'uploads/17d99b818a.jpg', 'Iconic shapes, classic materials and Ray-Ban dna details define the unique identity of a new icon: club round, a marriage between a club master and a round shape. The club round heralds a new beacon of retro inspired cool\r\nCase included\r\nLenses are prescription ready (rx-able)\r\nNew club round shape club master meets round new addition to icons', 0),
(17, 'rayban_boyfriend_noir_marron_degrade', '£284.40 ', 'uploads/c6e8f59409.jpg', 'Ray-Ban RB4147 sunglasses are fashionable and bold with larger rounded square lenses in propionate plastic frames which offer maximum sun protection while embracing a chic Hollywood look', 0),
(18, 'rayban_justin_marron_vertDegrade', '$143.00 ', 'uploads/0e01782a68.jpg', 'Ray-Ban Justin sunglasses may just be one of the coolest looks in the Ray-Ban collection. Inspired by the iconic Wayfarer sunglasses, this style has been redesigned with slightly larger rectangle lenses, fresh new frame colors, stunning colored lenses and a rubberized frame finish to really give it that extra edge. Justin RB4165 sunglasses are bold, fun and unforgettable.\r\n\r\nPackage Dimensions: 6.8 x 3.5 x 1.8 inches\r\nShipping Weight: 4 ounces (View shipping rates and policies)\r\nASIN: B01695DHGS\r\nDate first listed on Amazon: October 6, 2015\r\nAmazon Best Sellers Rank: #2,507,284 in Clothing, Shoes & Jewelry (See Top 100 in Clothing, Shoes & Jewelry)\r\n#20883 in Women''s Sunglasses\r\nAverage Customer Review: Be the first to review this item', 0),
(19, 'rayban_round_or_vert', '$13.99 ', 'uploads/60c80e5383.jpg', 'HMIAO is keen on providing premium quality sunglasses with reasonable price.A bunch of models of sunglasses are available: classic aviator model, small round vintage model, small size geometric retro model, sports sunglasses and more. Just enter HMIAO SUNGLASSES and you will see.\r\nWe are proud of our services. Let us know about your experience of wearing HMIAO eyewear, we are always ready for making your purchase a happy experience. ', 0),
(20, 'rayban_justin_noir_bleuMirroir', '$203.00', 'uploads/17a6b1ae23.jpg', 'Ray-Ban is the world''s most iconic eyewear brand and is a global leader in its sector. Every model in the Ray-Ban collection is the product of meticulous, original styling that translates the best of the latest fashion trends into an ever-contemporary look for millions of Ray-Ban wearers around the world. From the early Aviator style that emerged in 1937 to the introduction of the classic Wayfarer in 1952, Ray-Ban is a brand that embodies America and adventure, great cities and wide-open spaces, heroism, individuality, and authenticity. Starting with a silver screen debut in 1961, Ray-Ban sunglasses have appeared throughout hundreds of films and have been a favorite on the Hollywood scene for years, both on and off the screen. With timeless and imaginative styles, Ray-Ban consistently blends high-tech design, lenses, and materials.  The collection remains true to its classic heritage while continuously evolving to meet today''s fashion demands.', 0),
(21, 'rayban_clubround_havaneNoir_vertClassique_g15', '$163.00 ', 'uploads/0188768197.jpg', 'Shipping Information: View shipping rates and policies\r\nASIN: B01DL8PPPM\r\nDate first listed on Amazon: March 29, 2016\r\nAmazon Best Sellers Rank: #9,950,203 in Clothing, Shoes & Jewelry (See Top 100 in Clothing, Shoes & Jewelry)\r\nAverage Customer Review: Be the first to review this item', 0),
(22, 'rayban_boyfriend_havane_marron_clair_degrade', 'AU $385.00', 'uploads/a0cd604590.jpg', 'Product Identifiers\r\nGTIN0710377980958\r\nBRANDRay-Ban\r\nMPNAZ58C2772B2523C\r\nUPC0710377980958\r\neBay Product ID (ePID)717115790\r\nProduct Key Features\r\nColourBrown\r\nLens ColourBrown\r\nFrame ColourBrown\r\nLens TechnologyGradient\r\nAdditional Product Features\r\nTypeWomen Sunglasses\r\nAge GroupAdult\r\nLens Width56mM\r\nGenderGirls', 0),
(23, 'rayban_new_wayfarer_havane_marron_clair_degrade', '564.31 SAR ', 'uploads/4966fd551e.jpg', 'BrandRay-Ban\r\nTemple Size58 mm\r\nTargeted GroupMen\r\nModel NumberRay-Ban 2132\r\nEAN-138053672562293\r\nItem EAN2724504872298\r\nASINB01F5K497Y\r\nColor\r\nLens ColorLight Havana\r\nRead less\r\nDESCRIPTION:\r\n100% UV PROTECTION: To protect your eyes from harmful UV rays, these Wayfarer sunglasses are polarized and coated with 100% UV protection. The 58 mm x 43 mm lenses are durable and polarized.', 0),
(24, 'rayban_predator_noir_gris_mirroir', '$143.00', 'uploads/0a471f8ef3.jpg', 'Look killer good in these sporty sunglasses. Lightweight plastic propionate frames. G-15xlt glass lenses absorb up to 70% of visible light and 100% of all UV and some blue light without altering color relationships. Base curve 8. Lenses are Rx-Able (prescription ready). Integrated nosepads. Brandmark at temples. Made in Italy. Case included. Dimensions:Lens 60mmW x 33mmHBridge 16mmTemple 124mm WARNING California''s Proposition 65 Measurements: Eye Size: 60 mm Bridge: 16 mm Temple Size: 130 mm Weight: 1.2 oz', 0),
(25, 'rayban_chris_noir_gun_bleu_ mirroir', '$203.00', 'uploads/cd0bffd856.jpg', 'Our sunglasses comply with UV400 standard, filtering out 100% of harmful UV radiation in the wavelength range up to 400nm. Trending fashion design. Suitable for men and women. These stunning aviator sunglasses are exquisitely crafted with a full metal frame. A modern touch on the classic aviator frame. Fashion blogger favorite. Take it home and never miss the trend.', 0),
(26, 'rayban_wayfarer_denimNoir_bleuMirroir', '$ 153.00', 'uploads/d943b22c7c.jpg', 'Brand Ray-Ban has always remained true to its original philosophy—even while experiencing significant growth in recent years. By emphasizing innovation, originality, quality and value Ray-Ban has refined its vision to earn worldwide recognition. Contemporary optical design, unparallel craftsmanship, outstanding warranty, and superior customer care defines Ray-Ban. Ray-Ban has made the ascent from humble beginnings—a boutique optical design company—to its present position: a worldwide leader in affordable luxury eyewear. Ray-Ban uses state-of-the-art materials to craft their signature eyewear frames: premium cellulose acetate, ultra-lightweight titanium, and color-rich stainless steel. Ray-Ban lenses are constructed from impact-resistant prescription material and provide 100% UV protection. They’re also scratch-resistant and coated with superhydrophobic and anti-reflective treatments at no additional cost. From the earliest design conversations, sophisticated eyewear brands such as Ray-Ban develops innovative designs that feature layers of depth through the finest materials in optical. This commitment to craftsmanship delivers unmatched quality and timeless style that transform glasses from pure function to coveted pieces.\r\n\r\n', 0),
(27, 'rayban_clubmaster_noir_bleuGris', 'US$150.15', 'uploads/ad59d9e53f.jpg', 'Shipping Weight: 181 g\r\nItem model number: RB 3016 49 120678\r\nASIN: B071P8PQW9\r\nDate first available at Amazon.ca: June 13 2017', 0),
(28, 'rayban_wayfarer_denimBleuClair_bleuDegrade', '$55.00', 'uploads/74c532724b.jpg', 'Ray-Ban Original Wayfarer Sunglasses (RB2140) Blue/Grey Cloth/Denim - Non-Polarized - 50mm', 0),
(29, 'rayban_justin_gris_argentDegrade', 'EUR 44.59', 'uploads/de132e64e8.jpg', 'Ray Ban RB4165 852/88 55M Rubber Grey/Grey Transp./Grey Silver Mirror Gradient', 0),
(30, 'rayban_new_wayfarer_havane_marronClassique_g15', '$143.00', 'uploads/4409e03073.jpg', 'Ray-Ban ® RB2132 New Wayfarer ® sunglasses are a slightly smaller interpretation on the most famous style in sunwear. The iconic Ray-Ban ® Wayfarer ® is immediately recognizable anywhere in the world. The Ray-Ban ® signature logo is displayed on both sculpted temples. The New Wayfarer ® flaunts a softer eye shape than the original and offers both classic and fashion bright color options. These sunglasses allow the wearer to enjoy a classic, celebrated style while adding their own individuality. The RB2132 New Wayfarer ® sunglasses are prescription friendly and come in polarized.', 0),
(31, 'rayban_predator_noir_vert_classique', '$143.00', 'uploads/b65e154c0e.jpg', 'Look killer good in these sporty sunglasses. Lightweight plastic propionate frames. G-15xlt glass lenses absorb up to 70% of visible light and 100% of all UV and some blue light without altering color relationships. Base curve 8. Lenses are Rx-Able (prescription ready). Integrated nosepads. Brandmark at temples. Made in Italy. Case included. Dimensions:Lens 60mmW x 33mmHBridge 16mmTemple 124mm WARNING California''s Proposition 65 Measurements: Eye Size: 60 mm Bridge: 16 mm Temple Size: 130 mm Weight: 1.2 oz', 0),
(32, 'rayban_chris_havane_gun_vert_classique', '$55.00', 'uploads/80bbf8dc9a.jpg', 'Product Identifiers\r\nBRANDRay-Ban\r\nMPN418771071\r\neBay Product ID (ePID)1569715452\r\nProduct Key Features\r\nGenderUnisex', 0),
(33, 'rayban_doubleBridge_bleu_gradient_flash', '$315.00', 'uploads/da706793e9.jpg', 'Case included\r\nLenses are prescription ready (rx-able)\r\nThe new full-metal round double bridge reinvents authentic RB design to create an all-new unisex icon, incorporating round, lightweight metal and brilliant lens options.\r\nunisex rounded metal frame in shiny gold with a cool and sun protective gradient brown mirror blue lens. option to rx.', 0),
(34, 'rayban_caravan_bronze_cuivre_bleu_miroir', '$ 153.00', 'uploads/92d83bbca5.jpg', 'Model code: RB3136 001 55-15\r\n\r\nOriginally launched in 1957, Ray-Ban Caravan sunglasses are a streamlined, geometric model and an alternative to the classic Aviator Sunglasses . The Ray-Ban signature logo is displayed on the nose pads and lenses. The Caravan features Square Sunglasses lenses and frames, as opposed to the teardrop lens shape sunglasses seen in the Aviator. \r\n\r\nWear Caravan RB3136 sunglasses in a gunmetal, gold or silver metal frame and lens treatments including crystal green solid, crystal grey mirror or prescription.', 0),
(35, 'rayban_wayfarer_havane_marron', '$196.67', 'uploads/a76b966fcb.jpg', 'Item specifics\r\nCondition:	\r\nNew with tags: A brand-new, unused, and unworn item (including handmade items) in the original packaging (such as ... Read more\r\nBrand:	Ray-Ban\r\nCountry/Region of Manufacture:	Italy	Frame Color:	Tortoise\r\nModel:	RB2140 902/57	Lens Color:	Brown Polarized\r\nSize:	50-22-150	Style:	Wayfarer\r\nLen''s Technology:	Glass	Frame Material:	Plastic / Metal / Glass\r\nMPN:	2140	Protection:	100% UVA & UVB\r\nLens Technology:	Polarized	Gender:	Unisex\r\nTemple Length:	150 mm	UPC:	805289126652', 0),
(36, 'rayban_clubmaster_havane_vert', '?7825.76 with GST', 'uploads/c3aeb16951.jpg', 'Ray-Ban RB3016 Medium (Size-51) Tortoise Green Men w0366 Sunglasses\r\nBrand: Ray Ban sunglasses, Product Type: Sunglasses, Frame Type: Full Rim Sunglasses, Frame Shape: Wayfarer, Gender: Men\r\n\r\nWho knew half rimmed glasses would ever be in again? Well, fashion has a way of surprising us. This pair of Ray-Bans sets itself apart from the common and gives you a look that will make you stand out. It is designed to compliment any aspect of your wardrobe. You can be dead sure this will give you the look of power and swag. This pair is branded as the Clubmaster- so you should be guaranteed a look that masters style.\r\n\r\nTortoise W0366 Frame.\r\n Tortoise Lens - Green Complete with Ray-Ban box, case and lens cloth\r\n. The 3016 is the classic Clubmaster by Ray-Ban.\r\n It boasts a vintage pin hinge and is perfect for those who aspire to some iconic status.\r\nIt is a great frame for making a fashionable statement and creating a retro look.\r\n Favoured by celebs as their beloved frame of the summer, this is a pair of sunglasses that will ensure your looking hot from season to season.\r\nSize Guide - Small - 47mm Large - 51mm', 0),
(37, 'rayban_wayfarer_noir_vert', '$55.00', 'uploads/21df0cd24f.jpg', 'Ray-Ban Original Wayfarer Fleck sunglassses. Premium acetate frame. Shiny black temples. Distincticve 3D rivets. Imported. Vendor style #: RB2140 1160.', 0),
(38, 'rayban_clubmaster_noir_marronDegrade', '$171.00', 'uploads/2452b58581.jpg', 'Frame Material: Nylon. Frame Color: Tortoise. Lens Color: Green. Lens Size: 49.', 0),
(39, 'rayban_round_doubleBridge_argent_gradient_flash', '£ 136.00', 'uploads/7545bb1fb1.jpg', 'Model code: RB3647N 001 51-22\r\n\r\nThe new full metal round double bridge reinvents authentic DNA design to create an all-new Ray-Ban icon, disrupting the concept of iconic design with a revolutionary statement of must-have style.\r\nFeaturing minimalistic volumes in easy to wear tones of gold or black and flat flash gradient lenses, this slick style offers contemporary individuals a passe-partout look with irresistible contemporary appeal – dress it up, or dress it down, a true icon knows no limits!', 0),
(40, 'rayban_andy_bleu_bleu_mirroir', '$ 153.00', 'uploads/55e2b57a41.jpg', 'Ray-Ban Sunglasses Andy 4202 607055 Matt Blue Blue Flash Mirror taken from the young collection this is a reworked aviator style with a futuristic shape, gummy textured finish and a really curvy shape that wraps a bit, dips a bit and sweeps a bit for sensational style and on trend looks.', 0),
(41, 'rayban_caravan_bronze_cuivre_lilas_mirroir', 'RM 613.74', 'uploads/a4142363f2.jpg', 'Product Description\r\nRay-Ban RB3136 Caravan Sunglasses were introduced by Ray-Ban in 1957 as a geometric alternative to original Aviators. Caravans feature a squared off lens instead of the classic teardrop Pilot shape. Available with prescription here Unisex Full rim metal frame \r\nFeature\r\nRay Ban Eyewear \r\nModel: RX3136 \r\nColor Code: 167/4K Bronze Copper \r\nDesigner eyewear comes with an original case and cleaning cloth. \r\nWe handle prescription orders! Email us for details! Visit our storefront: www.amazon.com/shops/A1WUXX7TFM8VUI \r\nBrand : Ray-Ban \r\nItem model num : RB3136 \r\nEAN : 0673424232847 \r\nPackage Dimensions(LxWxH) : 20x7x5cm ; 91 g', 0),
(42, 'rayban_round_doubleBridge_or_marron_classique_b15', '$315.00', 'uploads/90aea82c66.jpg', 'Case included\r\nLenses are prescription ready (rx-able)\r\nThe new full-metal round double bridge reinvents authentic RB design to create an all-new unisex icon, incorporating round, lightweight metal and brilliant lens options.\r\nunisex rounded metal frame in shiny gold with a cool and sun protective gradient brown mirror blue lens. option to rx.', 0),
(43, 'rayban_andy_noir_vert_classique', '$143.00', 'uploads/dd6bd8c282.jpg', 'New Ray Ban Youngster RB4202 606971 Matte Black/Dark Green 55mm Sunglasses', 0),
(44, 'rayban_chris_noir_argent_gris_degrade', '$228.23', 'uploads/cd2fbc3d5b.jpg', 'The RB4187 Chris Sunglasses from Ray-Ban features branded lenses and arm and this sunglass is from the Highstreet collection. This sunglass comes in Black design. Lenses: Grey Gradient.', 0),
(45, 'rayban_round_or_marronClairDegrade', '	US $79.98', 'uploads/9b116e1f9a.jpg', 'Item specifics\r\nCondition:	\r\nNew with tags: A brand-new, unused, and unworn item (including handmade items) in the original packaging (such as ... Read more\r\nGender:	Unisex\r\nLens Technology:	Gradient	Country/Region of Manufacture:	Italy\r\nFrame Material:	Metal	Style:	Round\r\nLens Color:	Brown	Protection:	100% UVA & UVB\r\nBrand:	\r\nRay-Ban\r\nTemple Length:	145\r\nFrame Color:	Gold	Theme:	Round', 0),
(46, 'rayban_justin_violet_violetMirroir', '$143.00', 'uploads/d373b6c267.jpg', 'Brand Ray-Ban has always remained true to its original philosophy—even while experiencing significant growth in recent years. By emphasizing innovation, originality, quality and value Ray-Ban has refined its vision to earn worldwide recognition. Contemporary optical design, unparallel craftsmanship, outstanding warranty, and superior customer care defines Ray-Ban. Ray-Ban has made the ascent from humble beginnings—a boutique optical design company—to its present position: a worldwide leader in affordable luxury eyewear. Ray-Ban uses state-of-the-art materials to craft their signature eyewear frames: premium cellulose acetate, ultra-lightweight titanium, and color-rich stainless steel. Ray-Ban lenses are constructed from impact-resistant prescription material and provide 100% UV protection. They’re also scratch-resistant and coated with superhydrophobic and anti-reflective treatments at no additional cost. From the earliest design conversations, sophisticated eyewear brands such as Ray-Ban develops innovative designs that feature layers of depth through the finest materials in optical. This commitment to craftsmanship delivers unmatched quality and timeless style that transform glasses from pure function to coveted pieces.', 0),
(47, 'rayban_clubround_havaneNoir_marronClassique_b15', '$163.00', 'uploads/ae971abe60.jpg', 'Shipping Information: View shipping rates and policies\r\nASIN: B01DL8PQQU\r\nDate first listed on Amazon: March 29, 2016\r\nAmazon Best Sellers Rank: #12,596,016 in Clothing, Shoes & Jewelry (See Top 100 in Clothing, Shoes & Jewelry)\r\nAverage Customer Review: Be the first to review this item', 0),
(48, 'rayban_boyfriend_noir_gris_classique', '$315.00', 'uploads/3fff6e3add.jpg', 'A modernized wayfarer, this pair of sunglasses from Ray-Ban is versatile, stylish, and totally fashion forward. With its clean lines, it''s made to stand out, while the UV lenses, logoed ear pieces, and integrated nose pads always take comfort and wearability into consideration.\r\n\r\nRay-Ban is the world''s most iconic eyewear brand and is a global leader in its sector. Every model in the Ray-Ban collection is the product of meticulous, original styling that translates the best of the latest fashion trends into an ever-contemporary look for millions of Ray-Ban wearers around the world. From the early Aviator style that emerged in 1937 to the introduction of the classic Wayfarer in 1952, Ray-Ban is a brand that embodies America and adventure, great cities and wide-open spaces, heroism, individuality, and authenticity. Starting with a silver screen debut in 1961, Ray-Ban sunglasses have appeared throughout hundreds of films and have been a favorite on the Hollywood scene for years, both on and off the screen. With timeless and imaginative styles, Ray-Ban consistently blends high-tech design, lenses, and materials. The collection remains true to its classic heritage while continuously evolving to meet today''s fashion demands.', 0),
(49, 'rayban_chris_bleu_argent_bleu_clair_degrade', '$ 143.00', 'uploads/191122d5de.jpg', 'Model code: RB4187 622/8G 54-18\r\n\r\nRay-Ban Chris sunglasses are a stylish new addition to the Highstreet collection. These unisex sunglasses are designed with unique style cues taken from the Erika style, but spun into a slightly more masculine shape with square lenses and a less circular frame shape. Chris RB4187 sunglasses have been crafted with a gummy and rubberized frame finish, giving these trend setting sunglasses an exclusive textured feel. The Ray-Ban Chris epitomizes modern day fashion packed into a lightweight, comfortable design. Choose Chris in traditional black or tortoise frames or some bolder frame colors such as blue, green and red that will ensure you don''t go unnoticed.', 0),
(50, 'rayban_erika_havaneGun_marronDegrade', '$ 163.00', 'uploads/8419032a68.jpg', 'Model code: RB4171 710/T5 54-18\r\n\r\nColor your world and complement your look with perfect glare free vision. Erika frames are the perfect accessory with conventional facades or light rubber, metal branches and camber tone that will set you apart from the crowd. The round shaped oversized lenses provide 100% UV protection and the polarised lenses block 99% of reflected light for enhanced vision. The flexible bridge adds a twist to the modern design. Look great and see even better in the Polarised Erika frames.', 0),
(51, 'rayban_clubround_bleu_argent_flash', '$153', 'uploads/95a793b4b6.jpg', 'Product Identifiers\r\nBRANDRay-Ban\r\nMPNRB42469843051MM\r\neBay Product ID (ePID)590888896\r\nProduct Key Features\r\nFrame MaterialPlastic\r\nLens TechnologyMirrored\r\nProtection100% UV\r\nLens ColorSilver\r\nGenderUnisex\r\nTemple Length145 mm\r\nFrame ColorBlack', 0),
(52, 'rayban_boyfriend_havane_gris_degrade_mirroir', '$ 153.00', 'uploads/6504380517.jpg', 'Product Identifiers\r\nBRANDRay-Ban\r\nMPNSU59783996CE3E7US\r\neBay Product ID (ePID)2145244895', 0),
(53, 'rayban_justin_noir_bleu', '$ 163.00', 'uploads/0dadc5f1b9.jpg', 'Model code: RB4165 622/T3 55-16\r\n\r\nOne up your game with the Ray-Ban Justin, one of the coolest looks in the Ray-Ban collection now with polarised lenses. Inspired by the iconic Wayfarer model, Justin offers a bold rubber finish to give a special touch to your style. Choose from solid or contrasting color frames and perfectly glare free polarized lenses. Look as good as you see on this unique upgrade to a Ray-Ban.', 0),
(54, 'rayban_new_wayfarer_noir_gris_bleu_degrade', '? 11,930', 'uploads/e65e297b1b.jpg', 'Model: RB2132.\r\nOriginal Ray Ban Packaging, Case and Cleaning Cloth included.\r\nGender: Unisex.\r\nPlastic Lens/ Non-Polarized Lens\r\nMade in Italy', 0),
(55, 'rayban_boyfriend_havane_marron_classique', '$ 193.00', 'uploads/43b8513231.jpg', 'Model code: RB4147 710/57 60-15\r\n\r\nRay-Ban ® RB4147 sunglasses are fashionable and bold with larger rounded square lenses in propionate plastic frames which offer maximum sun protection while embracing a chic Hollywood look. \r\n\r\nRay-Ban sunglasses come in classic frame colors like black and tort with gradient colored or polarized lenses. These larger sunglasses flatter most face shapes. \r\n\r\nPrescription friendly.', 0),
(56, 'rayban_erika_havaneGun_marronDegrade', '$ 163.00', 'uploads/551fe9be38.jpg', 'Model code: RB4171 710/T5 54-18\r\n\r\nColor your world and complement your look with perfect glare free vision. Erika frames are the perfect accessory with conventional facades or light rubber, metal branches and camber tone that will set you apart from the crowd. The round shaped oversized lenses provide 100% UV protection and the polarised lenses block 99% of reflected light for enhanced vision. The flexible bridge adds a twist to the modern design. Look great and see even better in the Polarised Erika frames.', 0),
(57, 'rayban_chris_noir_gun_argent_ mirroir', '$315.00', 'uploads/65dd429a6c.jpg', 'Rb4202 brings fresh frame colors, stunning mirrored lenses and a unique rubberized frame finish to your look. With frame color options such as violet, turquoise, black and blue, these cutting-edge sunglasseswill not only bring excitement to your life, but will also add some edge to your style. \r\n\r\nRay-Ban is the world''s most iconic eyewear brand and is a global leader in its sector. Every model in the Ray-Ban collection is the product of meticulous, original styling that translates the best of the latest fashion trends into an ever-contemporary look for millions of Ray-Ban wearers around the world. From the early Aviator style that emerged in 1937 to the introduction of the classic Wayfarer in 1952, Ray-Ban is a brand that embodies America and adventure, great cities and wide-open spaces, heroism, individuality, and authenticity. Starting with a silver screen debut in 1961, Ray-Ban sunglasses have appeared throughout hundreds of films and have been a favorite on the Hollywood scene for years, both on and off the screen. With timeless and imaginative styles, Ray-Ban consistently blends high-tech design, lenses, and materials.  The collection remains true to its classic heritage while continuously evolving to meet today''s fashion demands.', 0),
(58, 'rayban_wayfarer_biColorNoirJaune_jauneFlash', 'USD 19.99', 'uploads/edff698e2e.jpg', '\r\nray ban wayfarer black frame light brown mirror gold lenses 50mm non polarized', 0),
(59, 'rayban_justin_havane_gris', '$143.00', 'uploads/6586cb5be9.jpg', 'Package Dimensions: 6.4 x 2.8 x 1.7 inches\r\nShipping Weight: 4.05 pounds (View shipping rates and policies)\r\nASIN: B016PIOM2M\r\nItem model number: RB4165\r\nDate first listed on Amazon: October 16, 2015\r\nAmazon Best Sellers Rank: #5,474,889 in Clothing, Shoes & Jewelry (See Top 100 in Clothing, Shoes & Jewelry)\r\n#34971 in Men''s Sunglasses\r\n#4043 in Men''s Contemporary & Designer Sunglasses\r\n#3700 in Women''s Contemporary & Designer Sunglasses', 0),
(60, 'rayban_new_wayfarer_havane_bleu_vert_degrade', '$143.00', 'uploads/75125d6724.jpg', 'Konalla specializes in classic designed fashion sunglasses for different people. Fashion design, easier to dress collocation, the integration of art and science and technology, manifests individual character and individual style. Especially, glare eliminating and high definition vision. UV400 Lenses provide maximum HD vision and decrease sun glare. Now you can see clearer and farther than ever before. To make our products different from other products on the market.', 0),
(61, 'rayban_boyfriend_noir_gris_clair_degrade', '$105.05', 'uploads/1377b35df2.jpg', '\r\nCondition:	\r\nNew with tags: A brand-new, unused, and unworn item (including handmade items) in the original packaging (such as the original box or bag) and/or with the original tags attached.\r\ndefinitions	Brand:	\r\nRay Ban\r\nLens Color:	Grey	Frame Material:	Acetate\r\nLens Material:	Polycarbonate	Lens Bridge:	15\r\nGender:	Unisex	Lens Temple:	145\r\nFrame Colour:	Black	Frame Style:	Full Rim\r\nFrame Type:	Wayfarer	Frame Color:	Black', 0),
(62, 'rayban_chris_orange_argent_rouge_ mirroir', '$ 143.00', 'uploads/a6b766a48a.jpg', 'Model code: RB4187 631611 54-18\r\n\r\nRay-Ban Chris sunglasses are a stylish new addition to the Highstreet collection. These unisex sunglasses are designed with unique style cues taken from the Erika style, but spun into a slightly more masculine shape with square lenses and a less circular frame shape. Chris RB4187 sunglasses have been crafted with a gummy and rubberized frame finish, giving these trend setting sunglasses an exclusive textured feel. The Ray-Ban Chris epitomizes modern day fashion packed into a lightweight, comfortable design. Choose Chris in traditional black or tortoise frames or some bolder frame colors such as blue, green and red that will ensure you don''t go unnoticed.', 0),
(63, 'rayban_wayfarer_biColorNoirVert_vertFlash', '$122.50 - $153.00', 'uploads/8bf78787fc.jpg', 'Ray-Ban brings a modern twist to a classic style with fresh colors and lens tints. The Original Wayfarer offers options for everyone - whether you''re a sneaker-collecting hipster, or you''ve just been wearing these for 20+ years. Ray-Ban''s legendary reputation for optical quality was built on these shades - there''s a reason the Wayfarer is one of the most-copied sunglass designs of all time.', 0),
(64, 'rayban_justin_noir_vert', '$10.99', 'uploads/e2abf1fac4.jpg', 'Improved Comfort -Durable nylon frame construction is more flexible and lightweight than tradition plastic sunglasses making it ideal for outdoor sports activities such as baseball, motorcycle and cycling bicycle riding, driving, trail running, fishing, racing, skiing, climbing, trekking, golfing, snowboarding or driving with bright sunlight. Polycarbonate lens are impact, scratch resistant, durable and unbreakable. Strong, dark non-polarized lenses mean you can see your phone or tablet without any distortion. Polarized lenses can be good but they are horrible when you want to look at a screen. Our lenses cause no distortion but still block all the glare.', 0),
(65, 'rayban_clubround_havane_vertClassique_g15', 'USD 19.99', 'uploads/ca25d2620d.jpg', 'Iconic shapes, classic materials and Ray-Ban dna details define the unique identity of a new icon: club round, a marriage between a club master and a round shape. The club round heralds a new beacon of retro inspired cool', 0),
(66, 'rayban_clubmaster_havane_marronDegrade', '$143.00', 'uploads/9b440e7363.jpg', 'Iconic shapes, classic materials and Ray-Ban dna details define the unique identity of a new icon: club round, a marriage between a club master and a round shape. The club round heralds a new beacon of retro inspired cool', 0),
(67, 'rayban_round_doubleBridge_cuivre_gradient_flash', '$315.00', 'uploads/9287a8834d.jpg', 'Case included\r\nLenses are prescription ready (rx-able)\r\nThe new full-metal round double bridge reinvents authentic RB design to create an all-new unisex icon, incorporating round, lightweight metal and brilliant lens options.', 0),
(68, 'rayban_andy_havane_argent_flash', '$163.00', 'uploads/6e2d752cc9.jpg', 'With a fresh twist on the iconic Wayfarer, Andy joins the family with a unique rubberized frame finish and bold colors. Add a little edge to your look.', 0),
(69, 'rayban_caravan_bronze_cuivre_violet_mirroir', '52.400 OMR', 'uploads/15a35c0828.jpg', 'Metal aviators with clear nose pads and slim top bar\r\n\r\nPrescription-ready lenses\r\n\r\nIncludes protective case\r\n\r\nRay-Ban products include an etched "RB" on the left lens. The RB is not a scratch or defect.\r\n\r\nThe shape and curvature of these sunglasses may need adjustments. Adjustments should only be made by a professional.\r\n\r\nImported from USA\r\n\r\nBrand Ray-Ban has always remained true to its original philosophy-even while experiencing significant growth in recent \r\nyears. By emphasizing innovation, originality, quality and value Ray-Ban has refined its vision to earn worldwide \r\nrecognition. Contemporary optical design, unparallel craftsmanship, outstanding warranty, and superior customer care \r\ndefines Ray-Ban. Ray-Ban has made the ascent from humble beginnings-a boutique optical design company-to its present \r\nposition: a worldwide leader in affordable luxury eyewear. Ray-Ban uses state-of-the-art materials to craft their \r\nsignature eyewear frames: premium cellulose acetate, ultra-lightweight titanium, and color-rich stainless steel. Ray-Ban \r\nlenses are constructed from impact-resistant prescription material and provide 100% UV protection. They''re also \r\nscratch-resistant and coated with superhydrophobic and anti-reflective treatments at no additional cost. From the \r\nearliest design conversations, sophisticated eyewear brands such as Ray-Ban develops innovative designs that feature \r\nlayers of depth through the finest materials in optical. This commitment to craftsmanship delivers unmatched quality and \r\ntimeless style that transform glasses from pure function to coveted pieces.\r\n\r\nShop the largest choice of Sunglasses online in the UAE. Browse thousands of great deals on ray-ban products with fast, free delivery.', 0),
(70, 'rayban_wayfarer_havane_marronClairDegrade', 'AU $248.71', 'uploads/804292c74e.jpg', 'Product Identifiers\r\nBRANDRay-Ban\r\nMPNSU5965E0B323DD7\r\neBay Product ID (ePID)16005742452\r\nProduct Key Features\r\nMaterialCrystal\r\nColourBrown\r\nAdditional Product Features\r\nTypeSunglasses\r\nLens TechnologyGradient', 0),
(71, 'rayban_justin_noir_grisDegrade', '$143.00', 'uploads/e18e6cb0a4.jpg', 'Ray-Ban Justin sunglasses may just be one of the coolest looks in the Ray-Ban collection. Inspired by the iconic Wayfarer sunglasses, this style has been redesigned with slightly larger rectangle lenses, fresh new frame colors, stunning colored lenses and a rubberized frame finish to really give it that extra edge. Justin RB4165F sunglasses are bold, fun and unforgettable.Lens-Bridge: 54mm-16mm Temple Length: 145mm. UV protection. Polarized. Imported.California Residents:WARNING PROP 65: The eyewear products in this store can expose you to the chemical Nickel (Metallic), which is known to the State of California to cause cancer, and Bisphenol A (BPA), which is known to the State of California to cause birth defects or other reproductive harm. For more information go to www.P65Warnings.ca.gov.', 0),
(72, 'rayban_new_wayfarer_havane_vertClassique_g15', '$143.00', 'uploads/96af7f4609.jpg', 'Ray-Ban RB2132 New Wayfarer sunglasses take the iconic shape of the Classic Wayfarer and infuse a slightly smaller frame and softer eye shape perfect for women and men. These unisex sunglasses are non-polarized. All Ray-Ban sunglasses are made from superior materials, and these unisex non-polarized sunglasses are no exception. RB2132 unisex Wayfarer frames are manufactured from durable nylon, making them lightweight and able to hold up against frequent use. Our Wayfarer sunglasses utilize famous G-15 lenses, which are prescription ready and made from glass.\r\n\r\nRay-Ban allows you to choose from a variety of frame colors and lens treatments including crystal green, brown or gradient styles. All Ray-Ban New Wayfarer Classic sunglasses are designed to offer an easy fit with a high level of visual clarity and protection. The sunglasses are available in a variety of size options to ensure a relaxed yet comfortable fit. Our glass lenses help protect your eyes against harmful UV rays and have been coated with 100% UV protection. Ray-Ban glasses are comprised of precision-cut lenses that reduce eye strain when worn.\r\n\r\nRay-Ban unisex sunglasses are comfortable and effective to wear on cloudy and hazy days, when the sun is bright, and during sunrise and sunset.\r\n\r\nWayfarers signify what the look of rock and roll is all about. Classically framed and completely iconic, this style from Ray-Ban is lightweight and durable and ready to exude some serious attitude. Includes a durable protective storage case.', 0),
(73, 'rayban_andy_havane_bleu_flash', '$163.00 ', 'uploads/b9443c858e.jpg', 'Adding a fresh twist to the Wayfarer family, Ray-Ban Andy joins the Highstreet Collection. Inspired by the iconic style, Andy RB4202 brings fresh frame colors, stunning mirrored lenses and a unique rubberized frame finish to your look. With frame color options such as violet, turquoise, black and blue, these cutting-edge sunglasses will not only bring excitement to your life, but will also add some edge to your style. Prepare to be the next fashion statement amongst your peers with the iconic Ray-Ban Andy, becoming unforgettable with these bold and fun frame colors.', 0),
(74, 'rayban_chris_noir_gris_degrade', '$228.23', 'uploads/5ea3426c2c.jpg', 'The RB4187 Chris Sunglasses from Ray-Ban features branded lenses and arm and this sunglass is from the Highstreet collection. This sunglass comes in Black design. Lenses: Grey Gradient.', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `static_sunglasses`
--
ALTER TABLE `static_sunglasses`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `vir_sunglasses`
--
ALTER TABLE `vir_sunglasses`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `static_sunglasses`
--
ALTER TABLE `static_sunglasses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `vir_sunglasses`
--
ALTER TABLE `vir_sunglasses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
